name: Deploy
  
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      id-token: 'write'
      pages: 'write'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        with:
          public_base_path: /
